# Generated by Django 6.0 on 2026-09-05 12:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaymentOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_number", models.CharField(db_index=True, max_length=50, unique=True)),
                ("resource_type", models.CharField(choices=[("course", "Course"), ("track", "Track"), ("exam", "Exam")], db_index=True, max_length=20)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("original_amount", models.DecimalField(blank=True, decimal_places=2, help_text="Original price before applying any discount.", max_digits=12, null=True)),
                ("discount_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), help_text="Total discount applied to this order.", max_digits=12)),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("processing", "Processing"), ("paid", "Paid"), ("failed", "Failed"), ("cancelled", "Cancelled"), ("expired", "Expired"), ("refunded", "Refunded")], db_index=True, default="pending", max_length=20)),
                ("gateway", models.CharField(blank=True, db_index=True, default="", max_length=50)),
                ("gateway_order_id", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("gateway_payment_id", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("gateway", models.CharField(db_index=True, max_length=50)),
                ("gateway_transaction_id", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(max_length=10)),
                ("status", models.CharField(choices=[("created", "Created"), ("pending", "Pending"), ("success", "Success"), ("failed", "Failed"), ("refunded", "Refunded")], db_index=True, default="created", max_length=20)),
                ("failure_reason", models.TextField(blank=True, default="")),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="PaymentWebhookEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("gateway", models.CharField(db_index=True, max_length=50)),
                ("event_id", models.CharField(db_index=True, max_length=255)),
                ("event_type", models.CharField(blank=True, default="", max_length=100)),
                ("payload", models.JSONField(default=dict)),
                ("signature", models.TextField(blank=True, default="")),
                ("processed", models.BooleanField(db_index=True, default=False)),
                ("processing_error", models.TextField(blank=True, default="")),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"ordering": ["-received_at"]},
        ),
    ]
