# Generated by Django 6.0 on 2026-09-05 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0002_initial"),
        ("payments", "0001_initial"),
        ("quiz", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentorder",
            name="coupon",
            field=models.ForeignKey(blank=True, help_text="Coupon applied to this order, if any.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name="payment_orders", to="quiz.coupon"),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="course",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="payment_orders", to="courses.course"),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="exam",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="payment_orders", to="quiz.exam"),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="track",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="payment_orders", to="quiz.examtrack"),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payment_orders", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="order",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="transactions", to="payments.paymentorder"),
        ),
        migrations.AddIndex(
            model_name="paymentwebhookevent",
            index=models.Index(fields=["gateway", "processed"], name="payments_pa_gateway_2dfdd9_idx"),
        ),
        migrations.AddConstraint(
            model_name="paymentwebhookevent",
            constraint=models.UniqueConstraint(fields=("gateway", "event_id"), name="unique_payment_webhook_event"),
        ),
        migrations.AddIndex(
            model_name="paymentorder",
            index=models.Index(fields=["user", "status"], name="payments_pa_user_id_367e5d_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentorder",
            index=models.Index(fields=["gateway", "gateway_order_id"], name="payments_pa_gateway_81c37c_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentorder",
            index=models.Index(fields=["gateway", "gateway_payment_id"], name="payments_pa_gateway_7bb41f_idx"),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(fields=["gateway", "gateway_transaction_id"], name="payments_pa_gateway_a15119_idx"),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(fields=["order", "status"], name="payments_pa_order_i_ed562a_idx"),
        ),
    ]
