# Generated by Django 6.0 on 2026-08-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesubscription',
            name='auto_renew',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursesubscription',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='coursesubscription',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursesubscription',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='coursesubscription',
            name='payment_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='coursesubscription',
            name='starts_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When access becomes valid.', null=True),
        ),
        migrations.AddField(
            model_name='coursesubscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='coursesubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='coursesubscription',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='coursesubscription',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When access expires. NULL means no expiry.', null=True),
        ),
        migrations.AlterField(
            model_name='coursesubscription',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Legacy compatibility flag. New business logic should prefer status and is_valid().'),
        ),
        migrations.AlterField(
            model_name='coursesubscription',
            name='payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coursesubscription',
            name='subscribed_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the subscription was created.'),
        ),
        migrations.AlterField(
            model_name='coursesubscription',
            name='subscribed_by_admin',
            field=models.BooleanField(db_index=True, default=False, help_text='Indicates that the subscription was granted manually by an administrator.'),
        ),
    ]
