# Generated by Django 6.0 on 2026-08-14 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursesubscription_auto_renew_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
