# Generated by Django 6.0 on 2026-08-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_delete_subscriptionplan'),
        ('subscriptions', '0007_remove_subscriptionplan_subscriptio_code_d07513_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subscription_plans',
            field=models.ManyToManyField(blank=True, related_name='course_access_courses', to='subscriptions.subscriptionplan'),
        ),
    ]
