# Generated by Django 6.0 on 2026-08-25 20:09

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
import quiz.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExamUnlockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='exam_pass', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read_by', models.JSONField(blank=True, default=dict, help_text='Map user_id -> true')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('payment_method', models.CharField(choices=[('upi', 'UPI'), ('bank', 'Bank Transfer'), ('cash', 'Cash'), ('other', 'Other')], max_length=20)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_admin', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attempted', models.PositiveIntegerField(default=0)),
                ('total_correct', models.PositiveIntegerField(default=0)),
                ('last_practice_date', models.DateField(blank=True, null=True)),
                ('streak', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('single', 'Single Choice'), ('multi', 'Multiple Choice'), ('tf', 'True / False'), ('dropdown', 'Dropdown'), ('fill', 'Fill in the Blank'), ('numeric', 'Numeric'), ('match', 'Matching'), ('order', 'Ordering')], default='single', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(help_text='Question text')),
                ('explanation', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Explanation shown after answer submission.', null=True)),
                ('correct_text', models.TextField(blank=True, null=True)),
                ('numeric_answer', models.FloatField(blank=True, null=True)),
                ('numeric_tolerance', models.FloatField(default=0)),
                ('matching_pairs', models.JSONField(blank=True, null=True)),
                ('ordering_items', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussion_type', models.CharField(choices=[('comment', 'Comment'), ('doubt', 'Doubt'), ('correction', 'Correction'), ('explanation', 'User Explanation')], default='comment', max_length=20)),
                ('content', models.TextField()),
                ('is_answer_incorrect', models.BooleanField(default=False)),
                ('is_staff_verified', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_resolved', models.BooleanField(default=False, help_text='Whether staff has resolved this feedback')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('is_answer_incorrect', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('staff_note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionQualitySignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confusing', models.BooleanField(default=False)),
                ('explanation_helpful', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.PositiveIntegerField(choices=[(7, '7-Day Crash Plan'), (15, '15-Day Balanced Plan'), (30, '30-Day Mastery Plan')])),
                ('total_days', models.PositiveIntegerField()),
                ('questions_per_day', models.PositiveIntegerField()),
                ('question_ids', models.JSONField(default=list, help_text='Ordered question IDs for entire plan')),
                ('daily_progress', models.JSONField(default=dict, help_text='Map day_index -> completed_count')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('extension_days', models.PositiveIntegerField(default=0, help_text='Auto-extended days due to missed schedule')),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_attempted', models.PositiveIntegerField(default=0)),
                ('total_correct', models.PositiveIntegerField(default=0)),
                ('category_stats', models.JSONField(blank=True, default=dict)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('difficulty_stats', models.JSONField(blank=True, default=dict)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('performance_history', models.JSONField(blank=True, default=list)),
                ('exam_mode', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudyPlanAnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('accuracy', models.FloatField()),
                ('readiness', models.FloatField()),
                ('mastery', models.FloatField()),
                ('predicted_score', models.FloatField()),
                ('pass_probability', models.FloatField()),
                ('volatility', models.FloatField()),
                ('xp', models.PositiveIntegerField()),
                ('level', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent', models.PositiveIntegerField(default=0, help_text='Time spent on this question in seconds')),
                ('selections', models.JSONField(blank=True, null=True)),
                ('raw_answer', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('submitted', 'Submitted'), ('expired', 'Expired')], db_index=True, default='started', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('question_order', models.JSONField(default=list, help_text='Ordered list of question IDs')),
                ('current_index', models.PositiveIntegerField(default=0)),
                ('score', models.FloatField(blank=True, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
            ],
            bases=(quiz.utils.SafeStrMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DiscussionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Organization that owns this domain', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=200)),
                ('slug', models.SlugField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='organizations.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='quiz.category')),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='quiz.domain')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('question_count', models.PositiveIntegerField(default=10)),
                ('duration_seconds', models.PositiveIntegerField()),
                ('level', models.PositiveIntegerField(db_index=True, default=1)),
                ('passing_score', models.FloatField(default=50.0)),
                ('is_free', models.BooleanField(default=True, help_text='If checked, this exam is free')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Required only if exam is paid', max_digits=8, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('max_mock_attempts', models.PositiveIntegerField(default=3, help_text='Number of mock attempts allowed for this exam (0 = no mock)')),
                ('allow_review', models.BooleanField(default=True, help_text='If enabled, students can review answers before final submission.')),
                ('categories', models.ManyToManyField(blank=True, related_name='exams', to='quiz.category')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.category')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='organizations.organization')),
                ('prerequisite_exams', models.ManyToManyField(blank=True, related_name='unlocked_exams', to='quiz.exam')),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_converted', models.BooleanField(default=False, help_text='Set true once subscription is granted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.contactmethod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_leads', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_leads', to='quiz.exam')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('percent_off', models.PositiveIntegerField(blank=True, help_text='Percentage discount (0–100)', null=True)),
                ('flat_off', models.DecimalField(blank=True, decimal_places=2, help_text='Flat discount amount', max_digits=8, null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Maximum times this coupon can be used', null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('extra_trial_days', models.PositiveIntegerField(blank=True, help_text='Adds extra trial days when coupon is applied', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(blank=True, help_text='If set, coupon applies only to this exam', null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.exam')),
            ],
        ),
        migrations.CreateModel(
            name='ExamCategoryAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveIntegerField(default=0)),
                ('fixed_count', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.category')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='quiz.exam')),
            ],
        ),
        migrations.CreateModel(
            name='ExamTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='Unique inside organization')),
                ('description', models.TextField(blank=True)),
                ('subscription_scope', models.CharField(choices=[('track', 'Track'), ('exam', 'Exam')], default='track', max_length=10)),
                ('pricing_type', models.CharField(choices=[('free', 'Free'), ('monthly', 'Monthly'), ('lifetime', 'Lifetime')], default='free', help_text='Legacy pricing', max_length=20)),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('lifetime_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('trial_days', models.PositiveIntegerField(default=7, help_text='Legacy trial days')),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_tracks', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
