# Generated by Django 4.2 on 2025-12-06 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='quiz.category'),
        ),
        migrations.CreateModel(
            name='ExamCategoryAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveIntegerField(default=0, help_text='Percentage of exam questions from this category (0-100)')),
                ('fixed_count', models.PositiveIntegerField(blank=True, help_text='If set, allocate this many questions instead of using percentage', null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.category')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='quiz.exam')),
            ],
            options={
                'ordering': ('id',),
                'unique_together': {('exam', 'category')},
            },
        ),
    ]
