# Generated by Django 6.0 on 2026-09-15 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('organizations', '0002_initial'),
        ('quiz', '0001_initial'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examtrack',
            name='subscription_plans',
            field=models.ManyToManyField(blank=True, help_text='Track product plans available for this track. Exams are not sold through this relationship.', related_name='exam_tracks', to='subscriptions.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='enrollmentlead',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_leads', to='quiz.examtrack'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='track',
            field=models.ForeignKey(blank=True, help_text='If set, coupon applies only to this track.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to='quiz.examtrack'),
        ),
        migrations.AddField(
            model_name='examunlocklog',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.exam'),
        ),
        migrations.AddField(
            model_name='examunlocklog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='governmentbody',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='government_bodies', to='quiz.country'),
        ),
        migrations.AddField(
            model_name='governmentexamprogram',
            name='content_vertical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='government_exam_programs', to='quiz.contentvertical'),
        ),
        migrations.AddField(
            model_name='governmentexamprogram',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_programs', to='quiz.country'),
        ),
        migrations.AddField(
            model_name='governmentexamprogram',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='government_exam_programs', to='courses.course'),
        ),
        migrations.AddField(
            model_name='governmentexamprogram',
            name='government_body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_programs', to='quiz.governmentbody'),
        ),
        migrations.AddField(
            model_name='governmentexamstage',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='government_stages', to='quiz.exam'),
        ),
        migrations.AddField(
            model_name='governmentexamversion',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='quiz.governmentexamprogram'),
        ),
        migrations.AddField(
            model_name='governmentexamstage',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='quiz.governmentexamversion'),
        ),
        migrations.AddField(
            model_name='governmentjob',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='government_jobs', to='quiz.country'),
        ),
        migrations.AddField(
            model_name='governmentjob',
            name='government_body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='government_jobs', to='quiz.governmentbody'),
        ),
        migrations.AddField(
            model_name='governmentexamprogram',
            name='jobs',
            field=models.ManyToManyField(blank=True, related_name='exam_programs', to='quiz.governmentjob'),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningactivitydismissal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_activity_dismissals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningshortlist',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_shortlists', to='courses.course'),
        ),
        migrations.AddField(
            model_name='learningshortlist',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_shortlists', to='quiz.exam'),
        ),
        migrations.AddField(
            model_name='learningshortlist',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_shortlists', to='quiz.examtrack'),
        ),
        migrations.AddField(
            model_name='learningshortlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_shortlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Leave empty to target all users (broadcast).', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_records', to='courses.course'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.exam'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_records', to='subscriptions.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.examtrack'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='practicestat',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.category'),
        ),
        migrations.AddField(
            model_name='practicestat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preparationprogram',
            name='content_vertical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preparation_programs', to='quiz.contentvertical'),
        ),
        migrations.AddField(
            model_name='preparationprogram',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preparation_programs', to='quiz.country'),
        ),
        migrations.AddField(
            model_name='preparationprogram',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='preparation_programs', to='courses.course'),
        ),
        migrations.AddField(
            model_name='preparationprogram',
            name='exams',
            field=models.ManyToManyField(blank=True, related_name='preparation_programs', to='quiz.exam'),
        ),
        migrations.AddField(
            model_name='question',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='All categories associated with this question. A question may belong to multiple categories.', related_name='questions', to='quiz.category'),
        ),
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization that owns this question.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='question',
            name='primary_category',
            field=models.ForeignKey(blank=True, help_text="Primary category used for the question's main classification.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_questions', to='quiz.category'),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.question'),
        ),
        migrations.AddField(
            model_name='questiondiscussion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='quiz.questiondiscussion'),
        ),
        migrations.AddField(
            model_name='questiondiscussion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='quiz.question'),
        ),
        migrations.AddField(
            model_name='questiondiscussion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_discussions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussionvote',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='quiz.questiondiscussion'),
        ),
        migrations.AddField(
            model_name='discussionreport',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='quiz.questiondiscussion'),
        ),
        migrations.AddField(
            model_name='questionfeedback',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='quiz.question'),
        ),
        migrations.AddField(
            model_name='questionfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionqualitysignal',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_signals', to='quiz.question'),
        ),
        migrations.AddField(
            model_name='questionqualitysignal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='domain',
            field=models.ForeignKey(blank=True, help_text='Optional domain focus', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.domain'),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studyplananalyticssnapshot',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='quiz.studyplan'),
        ),
        migrations.AddField(
            model_name='trackexam',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_memberships', to='quiz.exam'),
        ),
        migrations.AddField(
            model_name='trackexam',
            name='prerequisite_exams',
            field=models.ManyToManyField(blank=True, help_text='Exams that must be passed before this track exam is available.', related_name='track_prerequisite_memberships', to='quiz.exam'),
        ),
        migrations.AddField(
            model_name='trackexam',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_exams', to='quiz.examtrack'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.choice'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
        ),
        migrations.AddField(
            model_name='userexam',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.exam'),
        ),
        migrations.AddField(
            model_name='userexam',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.userexam'),
        ),
        migrations.AddField(
            model_name='questionfeedback',
            name='user_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_feedbacks', to='quiz.userexam'),
        ),
        migrations.AddField(
            model_name='questiondiscussion',
            name='user_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussions', to='quiz.userexam'),
        ),
        migrations.AddIndex(
            model_name='couponredemption',
            index=models.Index(fields=['coupon', 'user'], name='coupon_redemption_user_idx'),
        ),
        migrations.AddIndex(
            model_name='couponredemption',
            index=models.Index(fields=['user', 'redeemed_at'], name='coupon_redemption_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='couponredemption',
            constraint=models.UniqueConstraint(fields=('coupon', 'user', 'order'), name='unique_coupon_user_order_redemption'),
        ),
        migrations.AlterUniqueTogether(
            name='domain',
            unique_together={('organization', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('organization', 'slug')},
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['organization', 'is_published'], name='exam_org_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='examcategoryallocation',
            index=models.Index(fields=['exam', 'category'], name='exam_cat_alloc_idx'),
        ),
        migrations.AddConstraint(
            model_name='examcategoryallocation',
            constraint=models.UniqueConstraint(fields=('exam', 'category'), name='unique_exam_category_alloc'),
        ),
        migrations.AlterUniqueTogether(
            name='examtrack',
            unique_together={('organization', 'slug')},
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_active', 'valid_from', 'valid_to'], name='coupon_active_valid_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examunlocklog',
            unique_together={('user', 'exam')},
        ),
        migrations.AddIndex(
            model_name='governmentbody',
            index=models.Index(fields=['country', 'is_active'], name='body_country_active_idx'),
        ),
        migrations.AddIndex(
            model_name='governmentbody',
            index=models.Index(fields=['country', 'name'], name='body_country_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='governmentbody',
            constraint=models.UniqueConstraint(fields=('country', 'code'), name='uniq_body_country_code'),
        ),
        migrations.AddIndex(
            model_name='governmentexamversion',
            index=models.Index(fields=['program', 'status'], name='version_program_status_idx'),
        ),
        migrations.AddIndex(
            model_name='governmentexamversion',
            index=models.Index(fields=['status', 'effective_from'], name='version_status_effective_idx'),
        ),
        migrations.AddConstraint(
            model_name='governmentexamversion',
            constraint=models.UniqueConstraint(fields=('program', 'version'), name='uniq_exam_program_version'),
        ),
        migrations.AddIndex(
            model_name='governmentexamstage',
            index=models.Index(fields=['version', 'is_active', 'order'], name='stage_version_active_order_idx'),
        ),
        migrations.AddIndex(
            model_name='governmentexamstage',
            index=models.Index(fields=['exam', 'is_active'], name='stage_exam_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='governmentexamstage',
            constraint=models.UniqueConstraint(fields=('version', 'code'), name='uniq_stage_version_code'),
        ),
        migrations.AddConstraint(
            model_name='governmentexamstage',
            constraint=models.UniqueConstraint(fields=('version', 'order'), name='uniq_stage_version_order'),
        ),
        migrations.AddIndex(
            model_name='governmentjob',
            index=models.Index(fields=['government_body', 'is_active'], name='job_body_active_idx'),
        ),
        migrations.AddIndex(
            model_name='governmentjob',
            index=models.Index(fields=['country', 'is_active'], name='job_country_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='governmentjob',
            constraint=models.UniqueConstraint(fields=('government_body', 'code'), name='uniq_job_body_code'),
        ),
        migrations.AddIndex(
            model_name='governmentexamprogram',
            index=models.Index(fields=['country', 'is_active'], name='program_country_active_idx'),
        ),
        migrations.AddIndex(
            model_name='governmentexamprogram',
            index=models.Index(fields=['government_body', 'is_active'], name='program_body_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='governmentexamprogram',
            constraint=models.UniqueConstraint(fields=('government_body', 'code'), name='uniq_program_body_code'),
        ),
        migrations.AddIndex(
            model_name='learningactivitydismissal',
            index=models.Index(fields=['user', 'resource_type', 'resource_id'], name='quiz_learni_user_id_aa8e86_idx'),
        ),
        migrations.AddConstraint(
            model_name='learningactivitydismissal',
            constraint=models.UniqueConstraint(fields=('user', 'resource_type', 'resource_id'), name='uniq_learning_activity_dismissal'),
        ),
        migrations.AlterUniqueTogether(
            name='practicestat',
            unique_together={('user', 'category')},
        ),
        migrations.AddIndex(
            model_name='preparationprogram',
            index=models.Index(fields=['content_vertical', 'is_active'], name='prep_prog_vert_act_idx'),
        ),
        migrations.AddIndex(
            model_name='preparationprogram',
            index=models.Index(fields=['country', 'is_active'], name='prep_prog_country_idx'),
        ),
        migrations.AddIndex(
            model_name='preparationprogram',
            index=models.Index(fields=['is_published', 'is_active'], name='prep_prog_pub_act_idx'),
        ),
        migrations.AddConstraint(
            model_name='preparationprogram',
            constraint=models.UniqueConstraint(fields=('content_vertical', 'code'), name='uniq_prep_program_vertical_code'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['primary_category', 'is_active', 'is_deleted'], name='q_primary_cat_active_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['organization', 'is_active', 'is_deleted'], name='question_org_active_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty', 'is_active', 'is_deleted'], name='question_difficulty_active_idx'),
        ),
        migrations.AddIndex(
            model_name='discussionvote',
            index=models.Index(fields=['discussion'], name='quiz_discus_discuss_7c338f_idx'),
        ),
        migrations.AddIndex(
            model_name='discussionvote',
            index=models.Index(fields=['value'], name='quiz_discus_value_69e945_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='discussionvote',
            unique_together={('user', 'discussion')},
        ),
        migrations.AlterUniqueTogether(
            name='discussionreport',
            unique_together={('user', 'discussion')},
        ),
        migrations.AlterUniqueTogether(
            name='questionqualitysignal',
            unique_together={('question', 'user')},
        ),
        migrations.AddIndex(
            model_name='studyplan',
            index=models.Index(fields=['user', 'is_active'], name='quiz_studyp_user_id_497cb0_idx'),
        ),
        migrations.AddIndex(
            model_name='studyplan',
            index=models.Index(fields=['user', 'is_completed'], name='quiz_studyp_user_id_ad8f16_idx'),
        ),
        migrations.AddIndex(
            model_name='trackexam',
            index=models.Index(fields=['track', 'order'], name='track_exam_order_idx'),
        ),
        migrations.AddIndex(
            model_name='trackexam',
            index=models.Index(fields=['exam'], name='track_exam_exam_idx'),
        ),
        migrations.AddConstraint(
            model_name='trackexam',
            constraint=models.UniqueConstraint(fields=('track', 'exam'), name='unique_track_exam'),
        ),
        migrations.AddIndex(
            model_name='userexam',
            index=models.Index(fields=['user', 'exam'], name='quiz_userex_user_id_8ef153_idx'),
        ),
        migrations.AddIndex(
            model_name='userexam',
            index=models.Index(fields=['user', 'submitted_at'], name='quiz_userex_user_id_ebd089_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['user_exam', 'question'], name='quiz_useran_user_ex_323355_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('user_exam', 'question')},
        ),
        migrations.AddIndex(
            model_name='questiondiscussion',
            index=models.Index(fields=['question'], name='quiz_questi_questio_a1f744_idx'),
        ),
        migrations.AddIndex(
            model_name='questiondiscussion',
            index=models.Index(fields=['discussion_type'], name='quiz_questi_discuss_da4886_idx'),
        ),
        migrations.AddIndex(
            model_name='questiondiscussion',
            index=models.Index(fields=['is_pinned'], name='quiz_questi_is_pinn_33d0c9_idx'),
        ),
        migrations.AddIndex(
            model_name='questiondiscussion',
            index=models.Index(fields=['created_at'], name='quiz_questi_created_7f0567_idx'),
        ),
    ]
