from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_learningactivitydismissal"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentVertical",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.SlugField(max_length=60, unique=True)),
                ("vertical_type", models.CharField(choices=[("professional_certification", "Professional Certification"), ("government_exam", "Government / Competitive Exam"), ("academic_exam", "Academic Exam"), ("skill_assessment", "Skill Assessment")], max_length=40, unique=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(max_length=3, unique=True)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="GovernmentBody",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("code", models.SlugField(max_length=100)),
                ("slug", models.SlugField(max_length=220)),
                ("official_website", models.URLField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="government_bodies", to="quiz.country")),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="GovernmentJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("code", models.SlugField(max_length=120)),
                ("slug", models.SlugField(max_length=280)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="government_jobs", to="quiz.country")),
                ("government_body", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="government_jobs", to="quiz.governmentbody")),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="GovernmentExamProgram",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("code", models.SlugField(max_length=140)),
                ("slug", models.SlugField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("official_website", models.URLField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content_vertical", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="government_exam_programs", to="quiz.contentvertical")),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="exam_programs", to="quiz.country")),
                ("government_body", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="exam_programs", to="quiz.governmentbody")),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="GovernmentExamVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.CharField(max_length=80)),
                ("slug", models.SlugField(max_length=180)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("active", "Active"), ("retired", "Retired")], db_index=True, default="draft", max_length=20)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("official_syllabus_url", models.URLField(blank=True)),
                ("official_notification_url", models.URLField(blank=True)),
                ("source_published_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("program", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="versions", to="quiz.governmentexamprogram")),
            ],
            options={"ordering": ["-effective_from", "-created_at"]},
        ),
        migrations.CreateModel(
            name="GovernmentExamStage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("code", models.SlugField(max_length=120)),
                ("order", models.PositiveIntegerField(default=1)),
                ("is_required", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("exam", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="government_stages", to="quiz.exam")),
                ("version", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stages", to="quiz.governmentexamversion")),
            ],
            options={"ordering": ["order", "id"]},
        ),
        migrations.AddField(
            model_name="governmentexamprogram",
            name="jobs",
            field=models.ManyToManyField(blank=True, related_name="exam_programs", to="quiz.governmentjob"),
        ),
        migrations.AddIndex(model_name="contentvertical", index=models.Index(fields=["vertical_type", "is_active"], name="vertical_type_active_idx")),
        migrations.AddIndex(model_name="country", index=models.Index(fields=["is_active", "name"], name="country_active_name_idx")),
        migrations.AddIndex(model_name="governmentbody", index=models.Index(fields=["country", "is_active"], name="body_country_active_idx")),
        migrations.AddIndex(model_name="governmentbody", index=models.Index(fields=["country", "name"], name="body_country_name_idx")),
        migrations.AddConstraint(model_name="governmentbody", constraint=models.UniqueConstraint(fields=("country", "code"), name="uniq_body_country_code")),
        migrations.AddIndex(model_name="governmentjob", index=models.Index(fields=["government_body", "is_active"], name="job_body_active_idx")),
        migrations.AddIndex(model_name="governmentjob", index=models.Index(fields=["country", "is_active"], name="job_country_active_idx")),
        migrations.AddConstraint(model_name="governmentjob", constraint=models.UniqueConstraint(fields=("government_body", "code"), name="uniq_job_body_code")),
        migrations.AddIndex(model_name="governmentexamprogram", index=models.Index(fields=["country", "is_active"], name="program_country_active_idx")),
        migrations.AddIndex(model_name="governmentexamprogram", index=models.Index(fields=["government_body", "is_active"], name="program_body_active_idx")),
        migrations.AddConstraint(model_name="governmentexamprogram", constraint=models.UniqueConstraint(fields=("government_body", "code"), name="uniq_program_body_code")),
        migrations.AddIndex(model_name="governmentexamversion", index=models.Index(fields=["program", "status"], name="version_program_status_idx")),
        migrations.AddIndex(model_name="governmentexamversion", index=models.Index(fields=["status", "effective_from"], name="version_status_effective_idx")),
        migrations.AddConstraint(model_name="governmentexamversion", constraint=models.UniqueConstraint(fields=("program", "version"), name="uniq_exam_program_version")),
        migrations.AddIndex(model_name="governmentexamstage", index=models.Index(fields=["version", "is_active", "order"], name="stage_version_active_order_idx")),
        migrations.AddIndex(model_name="governmentexamstage", index=models.Index(fields=["exam", "is_active"], name="stage_exam_active_idx")),
        migrations.AddConstraint(model_name="governmentexamstage", constraint=models.UniqueConstraint(fields=("version", "code"), name="uniq_stage_version_code")),
        migrations.AddConstraint(model_name="governmentexamstage", constraint=models.UniqueConstraint(fields=("version", "order"), name="uniq_stage_version_order")),
    ]
