# Generated by Django 4.2 on 2025-12-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_category_parent_examcategoryallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='exams', to='quiz.category'),
        ),
    ]
