# Generated by Django 4.2 on 2025-12-06 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0003_exam_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read_by', models.JSONField(blank=True, default=dict, help_text='map user_id->true')),
                ('users', models.ManyToManyField(blank=True, help_text='Leave empty to target all users (broadcast).', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
