# Generated by Django 4.2 on 2025-12-06 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='level',
            field=models.PositiveIntegerField(default=1, help_text='Progression level for this exam (1 = beginner).'),
        ),
        migrations.AddField(
            model_name='exam',
            name='passing_score',
            field=models.FloatField(default=50.0, help_text='Percentage required to pass (0-100).'),
        ),
        migrations.AddField(
            model_name='exam',
            name='prerequisite_exams',
            field=models.ManyToManyField(blank=True, help_text='If set, user must pass these exams before taking this exam.', related_name='dependent_exams', to='quiz.exam'),
        ),
        migrations.AddField(
            model_name='userexam',
            name='passed',
            field=models.BooleanField(blank=True, help_text='True if this attempt passed according to exam.passing_score', null=True),
        ),
    ]
