# Generated by Django 6.0 on 2025-12-24 14:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_question_explanation_questionfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamUnlockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='exam_pass', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attempted', models.PositiveIntegerField(default=0)),
                ('total_correct', models.PositiveIntegerField(default=0)),
                ('last_practice_date', models.DateField(blank=True, null=True)),
                ('streak', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='examcategoryallocation',
            options={},
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='time_spent',
            field=models.PositiveIntegerField(default=0, help_text='Time spent on this question in seconds'),
        ),
        migrations.AddField(
            model_name='userexam',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('submitted', 'Submitted'), ('expired', 'Expired')], db_index=True, default='started', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='level',
            field=models.PositiveIntegerField(db_index=True, default=1, help_text='1=Beginner, 2=Intermediate, 3=Advanced'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='passing_score',
            field=models.FloatField(default=50.0, help_text='Percentage required to pass'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='prerequisite_exams',
            field=models.ManyToManyField(blank=True, related_name='unlocked_exams', to='quiz.exam'),
        ),
        migrations.AlterField(
            model_name='examcategoryallocation',
            name='fixed_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examcategoryallocation',
            name='percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.choice'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='selections',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userexam',
            name='current_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userexam',
            name='passed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userexam',
            name='question_order',
            field=models.JSONField(default=list, help_text='Ordered list of question IDs'),
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('user_exam', 'question')},
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['user_exam', 'question'], name='quiz_useran_user_ex_323355_idx'),
        ),
        migrations.AddIndex(
            model_name='userexam',
            index=models.Index(fields=['user', 'exam'], name='quiz_userex_user_id_8ef153_idx'),
        ),
        migrations.AddIndex(
            model_name='userexam',
            index=models.Index(fields=['user', 'submitted_at'], name='quiz_userex_user_id_ebd089_idx'),
        ),
        migrations.AddConstraint(
            model_name='userexam',
            constraint=models.UniqueConstraint(condition=models.Q(('submitted_at__isnull', True)), fields=('user', 'exam'), name='one_active_attempt_per_exam'),
        ),
        migrations.AddField(
            model_name='category',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='quiz.domain'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('domain', 'slug')},
        ),
        migrations.AddField(
            model_name='exam',
            name='track',
            field=models.ForeignKey(blank=True, help_text='Parent exam track like SnowPro Core', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='quiz.examtrack'),
        ),
        migrations.AddField(
            model_name='examunlocklog',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.exam'),
        ),
        migrations.AddField(
            model_name='examunlocklog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='practicestat',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.category'),
        ),
        migrations.AddField(
            model_name='practicestat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='examunlocklog',
            unique_together={('user', 'exam')},
        ),
        migrations.AlterUniqueTogether(
            name='practicestat',
            unique_together={('user', 'category')},
        ),
    ]
