# Generated by Django 6.0 on 2025-12-24 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_difficulty_domain_examtrack_examunlocklog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate to revoke access without deleting history')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiry for paid / time-limited access', null=True)),
                ('payment_required', models.BooleanField(default=False, help_text='Was payment required for this subscription')),
                ('payment_id', models.CharField(blank=True, help_text='Gateway payment reference (Razorpay/Stripe)', max_length=100, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='quiz.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'exam'], name='quiz_examsu_user_id_bf1d3a_idx'), models.Index(fields=['is_active'], name='quiz_examsu_is_acti_a44ed8_idx')],
                'unique_together': {('user', 'exam')},
            },
        ),
    ]
