# Generated by Django 5.2.9 on 2025-12-29 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_examtrack_subscription_scope_examsubscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_free',
            field=models.BooleanField(default=True, help_text='If checked, this exam is free'),
        ),
        migrations.AddField(
            model_name='exam',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Required only if exam is paid', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='examtrack',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='examtrack',
            name='lifetime_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Required if pricing type is Lifetime', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='examtrack',
            name='monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Required if pricing type is Monthly', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='examtrack',
            name='pricing_type',
            field=models.CharField(choices=[('free', 'Free'), ('monthly', 'Monthly'), ('lifetime', 'Lifetime')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='examtrack',
            name='trial_days',
            field=models.PositiveIntegerField(default=7, help_text='Free trial duration (days)'),
        ),
        migrations.AddField(
            model_name='examtracksubscription',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='level',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='exam',
            name='passing_score',
            field=models.FloatField(default=50.0),
        ),
        migrations.AlterField(
            model_name='exam',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='quiz.examtrack'),
        ),
        migrations.AlterField(
            model_name='examtrack',
            name='subscription_scope',
            field=models.CharField(choices=[('track', 'Track'), ('exam', 'Exam')], default='track', max_length=10),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('percent_off', models.PositiveIntegerField(blank=True, help_text='Percentage discount (0–100)', null=True)),
                ('flat_off', models.DecimalField(blank=True, decimal_places=2, help_text='Flat discount amount', max_digits=8, null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Maximum times this coupon can be used', null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('extra_trial_days', models.PositiveIntegerField(blank=True, help_text='Adds extra trial days when coupon is applied', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(blank=True, help_text='If set, coupon applies only to this exam', null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.exam')),
                ('track', models.ForeignKey(blank=True, help_text='If set, coupon applies only to this track', null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.examtrack')),
            ],
        ),
    ]
