# Generated by Django 6.0 on 2025-12-24 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_examsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examtrack',
            name='subscription_scope',
            field=models.CharField(choices=[('track', 'Track-level subscription (all levels included)'), ('exam', 'Exam-level subscription (subscribe per level)')], default='track', help_text='Choose whether users subscribe to the entire track or individual exams (levels) under this track.', max_length=10),
        ),
        migrations.CreateModel(
            name='ExamTrackSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate to revoke access without deleting history')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('payment_required', models.BooleanField(default=False)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='quiz.examtrack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'track'], name='quiz_examtr_user_id_cf35ae_idx'), models.Index(fields=['is_active'], name='quiz_examtr_is_acti_7aa0ef_idx')],
                'unique_together': {('user', 'track')},
            },
        ),
    ]
