# Generated by Django 6.0 on 2025-12-29 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_examtrack_subscription_scope_examtracksubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_free',
            field=models.BooleanField(default=True, help_text='If checked, this exam is free'),
        ),
        migrations.AddField(
            model_name='exam',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Required only if exam is paid', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='examtrack',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='examtrack',
            name='is_free',
            field=models.BooleanField(default=True, help_text='If checked, this entire track is free'),
        ),
        migrations.AddField(
            model_name='examtrack',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Required only if track is paid', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='level',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='exam',
            name='passing_score',
            field=models.FloatField(default=50.0),
        ),
        migrations.AlterField(
            model_name='exam',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='quiz.examtrack'),
        ),
        migrations.AlterField(
            model_name='examtrack',
            name='subscription_scope',
            field=models.CharField(choices=[('track', 'Track-level subscription (all levels included)'), ('exam', 'Exam-level subscription (subscribe per level)')], default='track', max_length=10),
        ),
    ]
