# Generated by Django 5.2.9 on 2025-12-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_exam_currency_exam_is_free_exam_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='max_mock_attempts',
            field=models.PositiveIntegerField(default=3, help_text='Number of mock attempts allowed for this exam (0 = no mock)'),
        ),
    ]
