# Generated by Django 6.0 on 2025-12-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_exam_currency_exam_is_free_exam_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtrack',
            name='lifetime_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='examtrack',
            name='monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
