# Generated by Django 6.0 on 2025-12-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_examtrack_lifetime_price_examtrack_monthly_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtracksubscription',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
    ]
