# Generated by Django 6.0 on 2025-12-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_examtracksubscription_is_trial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('percent_off', models.PositiveIntegerField(blank=True, null=True)),
                ('flat_off', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
