# Generated by Django 6.0 on 2025-12-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examtrack',
            name='is_free',
        ),
        migrations.RemoveField(
            model_name='examtrack',
            name='price',
        ),
        migrations.AddField(
            model_name='examtrack',
            name='pricing_type',
            field=models.CharField(choices=[('free', 'Free'), ('monthly', 'Monthly'), ('lifetime', 'Lifetime')], default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='examtrack',
            name='subscription_scope',
            field=models.CharField(choices=[('track', 'Track'), ('exam', 'Exam')], default='track', max_length=10),
        ),
    ]
