# Generated by Django 6.0 on 2025-12-29 18:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_remove_examtrack_is_free_remove_examtrack_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='exam',
            field=models.ForeignKey(blank=True, help_text='If set, coupon applies only to this exam', null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.exam'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='extra_trial_days',
            field=models.PositiveIntegerField(blank=True, help_text='Adds extra trial days when coupon is applied', null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='track',
            field=models.ForeignKey(blank=True, help_text='If set, coupon applies only to this track', null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.examtrack'),
        ),
        migrations.AddField(
            model_name='examtrack',
            name='trial_days',
            field=models.PositiveIntegerField(default=7, help_text='Free trial duration (days)'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='flat_off',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Flat discount amount', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='percent_off',
            field=models.PositiveIntegerField(blank=True, help_text='Percentage discount (0–100)', null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum times this coupon can be used', null=True),
        ),
        migrations.AlterField(
            model_name='examtrack',
            name='lifetime_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Required if pricing type is Lifetime', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='examtrack',
            name='monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Required if pricing type is Monthly', max_digits=8, null=True),
        ),
    ]
