# Generated by Django 6.0 on 2025-12-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_coupon_created_at_coupon_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='max_mock_attempts',
            field=models.PositiveIntegerField(default=3, help_text='Number of mock attempts allowed for this exam (0 = no mock)'),
        ),
    ]
