# Generated by Django 6.0 on 2025-12-31 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_exam_max_mock_attempts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussion_type', models.CharField(choices=[('comment', 'Comment'), ('doubt', 'Doubt'), ('correction', 'Correction'), ('explanation', 'User Explanation')], default='comment', max_length=20)),
                ('content', models.TextField()),
                ('is_answer_incorrect', models.BooleanField(default=False)),
                ('is_staff_verified', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='quiz.questiondiscussion')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='quiz.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_discussions', to=settings.AUTH_USER_MODEL)),
                ('user_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussions', to='quiz.userexam')),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='quiz.questiondiscussion')),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='quiz.questiondiscussion')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionQualitySignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confusing', models.BooleanField(default=False)),
                ('explanation_helpful', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_signals', to='quiz.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='questiondiscussion',
            index=models.Index(fields=['question'], name='quiz_questi_questio_a1f744_idx'),
        ),
        migrations.AddIndex(
            model_name='questiondiscussion',
            index=models.Index(fields=['discussion_type'], name='quiz_questi_discuss_da4886_idx'),
        ),
        migrations.AddIndex(
            model_name='questiondiscussion',
            index=models.Index(fields=['is_pinned'], name='quiz_questi_is_pinn_33d0c9_idx'),
        ),
        migrations.AddIndex(
            model_name='questiondiscussion',
            index=models.Index(fields=['created_at'], name='quiz_questi_created_7f0567_idx'),
        ),
        migrations.AddIndex(
            model_name='discussionvote',
            index=models.Index(fields=['discussion'], name='quiz_discus_discuss_7c338f_idx'),
        ),
        migrations.AddIndex(
            model_name='discussionvote',
            index=models.Index(fields=['value'], name='quiz_discus_value_69e945_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='discussionvote',
            unique_together={('user', 'discussion')},
        ),
        migrations.AlterUniqueTogether(
            name='discussionreport',
            unique_together={('user', 'discussion')},
        ),
        migrations.AlterUniqueTogether(
            name='questionqualitysignal',
            unique_together={('question', 'user')},
        ),
    ]
