# Generated by Django 5.2.9 on 2026-01-04 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_question_deleted_at_question_deleted_by_and_more'),
        ('quiz', '0020_question_deleted_at_question_deleted_by_and_more'),
    ]

    operations = [
    ]
