# Generated by Django 6.0 on 2026-01-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_merge_20260104_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubscription',
            name='subscribed_by_admin',
            field=models.BooleanField(default=False, help_text='Granted manually by admin'),
        ),
        migrations.AddField(
            model_name='examtracksubscription',
            name='subscribed_by_admin',
            field=models.BooleanField(default=False, help_text='Granted manually by admin'),
        ),
    ]
