# Generated by Django 6.0 on 2026-01-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_contactmethod_enrollmentlead_paymentrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiondiscussion',
            name='is_resolved',
            field=models.BooleanField(default=False, help_text='Whether staff has resolved this feedback'),
        ),
    ]
