# Generated by Django 6.0 on 2026-01-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_questiondiscussion_is_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiondiscussion',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
    ]
