# Generated by Django 6.0 on 2026-01-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_questiondiscussion_severity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration_days', models.PositiveIntegerField(blank=True, help_text='NULL = lifetime access', null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='examtrack',
            name='lifetime_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='examtrack',
            name='monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='examtrack',
            name='pricing_type',
            field=models.CharField(choices=[('free', 'Free'), ('monthly', 'Monthly'), ('lifetime', 'Lifetime')], default='free', help_text='⚠ Legacy field (will be deprecated)', max_length=20),
        ),
        migrations.AddField(
            model_name='examtrack',
            name='subscription_plans',
            field=models.ManyToManyField(blank=True, help_text='Select pricing plans available for this track', related_name='tracks', to='quiz.subscriptionplan'),
        ),
    ]
