# Generated by Django 6.0 on 2026-01-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_subscriptionplan_alter_examtrack_lifetime_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtrack',
            name='pricing_type',
            field=models.CharField(choices=[('free', 'Free'), ('monthly', 'Monthly'), ('lifetime', 'Lifetime')], default='free', help_text='⚠ Legacy pricing (do not use with plans)', max_length=20),
        ),
        migrations.AlterField(
            model_name='examtrack',
            name='subscription_plans',
            field=models.ManyToManyField(blank=True, help_text='Pricing plans available for this track', related_name='tracks', to='quiz.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='examtrack',
            name='trial_days',
            field=models.PositiveIntegerField(default=7, help_text='Trial days (legacy only)'),
        ),
    ]
