# Generated by Django 6.0 on 2026-01-29 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0028_course_coursesection_lesson_courseenrollment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesection',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseenrollment',
            name='course',
        ),
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='courseenrollment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='section',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='practice_category',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='lesson',
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='user',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseEnrollment',
        ),
        migrations.DeleteModel(
            name='CourseSection',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='LessonProgress',
        ),
    ]
