# Generated by Django 6.0 on 2026-02-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0031_question_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsubscription',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examsubscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='examsubscription',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examsubscription',
            name='payment_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='examsubscription',
            name='subscribed_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='examtracksubscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='examtracksubscription',
            name='subscribed_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
