# Generated by Django 6.0 on 2026-02-12 13:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0032_alter_examsubscription_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useranswer',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
