# Generated by Django 6.0 on 2026-02-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0033_useranswer_started_at_useranswer_submitted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='userexam',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Duration of exam in minutes (0 = no timer)'),
        ),
    ]
