# Generated by Django 6.0 on 2026-02-12 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0034_remove_useranswer_started_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexam',
            name='duration_minutes',
        ),
    ]
