# Generated by Django 6.0 on 2026-02-20 08:50

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0036_alter_userexam_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Optional detailed explanation or solution shown on the result page.', null=True),
        ),
    ]
