# Generated by Django 6.0 on 2026-02-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0038_alter_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='allow_review',
            field=models.BooleanField(default=True, help_text='If enabled, students can review answers before final submission.'),
        ),
    ]
