# Generated by Django 6.0 on 2026-02-27 05:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0039_exam_allow_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.PositiveIntegerField(choices=[(7, '7-Day Crash Plan'), (15, '15-Day Balanced Plan'), (30, '30-Day Mastery Plan')])),
                ('total_days', models.PositiveIntegerField()),
                ('questions_per_day', models.PositiveIntegerField()),
                ('question_ids', models.JSONField(default=list, help_text='Ordered question IDs for entire plan')),
                ('daily_progress', models.JSONField(default=dict, help_text='Map day_index -> completed_count')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('extension_days', models.PositiveIntegerField(default=0, help_text='Auto-extended days due to missed schedule')),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(blank=True, help_text='Optional domain focus', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.domain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_active'], name='quiz_studyp_user_id_497cb0_idx'), models.Index(fields=['user', 'is_completed'], name='quiz_studyp_user_id_ad8f16_idx')],
            },
        ),
    ]
