# Generated by Django 6.0 on 2026-02-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0040_studyplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='category_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='total_attempted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='total_correct',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
