# Generated by Django 6.0 on 2026-02-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0042_studyplan_current_streak_studyplan_difficulty_stats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
