# Generated by Django 6.0 on 2026-02-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0043_studyplan_level_studyplan_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='exam_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='performance_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
