# Generated by Django 6.0 on 2026-03-02 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0044_studyplan_exam_mode_studyplan_performance_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlanAnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('accuracy', models.FloatField()),
                ('readiness', models.FloatField()),
                ('mastery', models.FloatField()),
                ('predicted_score', models.FloatField()),
                ('pass_probability', models.FloatField()),
                ('volatility', models.FloatField()),
                ('xp', models.PositiveIntegerField()),
                ('level', models.PositiveIntegerField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='quiz.studyplan')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
