# Generated by Django 6.0 on 2026-03-03 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_courseaccess'),
        ('quiz', '0045_studyplananalyticssnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='examtracksubscription',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_track_subscriptions', to='organizations.organization'),
        ),
    ]
