# Generated by Django 6.0 on 2026-03-04 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_courseaccess'),
        ('quiz', '0046_exam_organization_examtracksubscription_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtrack',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_tracks', to='organizations.organization'),
        ),
    ]
