# Generated by Django 6.0 on 2026-03-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_courseaccess'),
        ('quiz', '0047_examtrack_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examtrack',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='examtrack',
            name='pricing_type',
            field=models.CharField(choices=[('free', 'Free'), ('monthly', 'Monthly'), ('lifetime', 'Lifetime')], default='free', help_text='⚠ Legacy pricing (avoid when using subscription plans)', max_length=20),
        ),
        migrations.AlterField(
            model_name='examtrack',
            name='slug',
            field=models.SlugField(help_text='Unique inside organization'),
        ),
        migrations.AlterField(
            model_name='examtrack',
            name='subscription_plans',
            field=models.ManyToManyField(blank=True, help_text='Dynamic pricing plans available for this track', related_name='tracks', to='quiz.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='examtrack',
            name='trial_days',
            field=models.PositiveIntegerField(default=7, help_text='Trial days (legacy system)'),
        ),
        migrations.AlterUniqueTogether(
            name='examtrack',
            unique_together={('organization', 'slug')},
        ),
    ]
