# Generated by Django 6.0 on 2026-03-04 18:54

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_courseaccess'),
        ('quiz', '0048_alter_examtrack_options_alter_examtrack_pricing_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='domain',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 4, 18, 54, 56, 383305, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domain',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization that owns this domain', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=150),
        ),
        migrations.AlterField(
            model_name='domain',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('organization', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='domain',
            unique_together={('organization', 'slug')},
        ),
    ]
