# Generated by Django 6.0 on 2026-05-22 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_resourceassignment_assigned_by_and_more'),
        ('quiz', '0049_alter_category_options_alter_domain_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('NORMAL', 'Normal Exam'), ('COURSE', 'Course Exam'), ('MOCK', 'Mock Exam'), ('ASSESSMENT', 'Assessment')], db_index=True, default='NORMAL', help_text='Defines how this exam is used in the platform.', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='allow_review',
            field=models.BooleanField(default=True, help_text='Students can review answers before final submission.'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_exams', to='quiz.category'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration_seconds',
            field=models.PositiveIntegerField(help_text='Exam duration in seconds.'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_free',
            field=models.BooleanField(db_index=True, default=True, help_text='If enabled, students can access exam for free.'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='max_mock_attempts',
            field=models.PositiveIntegerField(default=3, help_text='0 means mock attempts disabled.'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Required only for paid exams.', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['exam_type', 'is_published'], name='quiz_exam_exam_ty_8962f8_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['organization', 'exam_type'], name='quiz_exam_organiz_6ae155_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['level'], name='quiz_exam_level_6c45ea_idx'),
        ),
    ]
