# Generated by Django 6.0 on 2026-09-05 12:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('org_owner', 'Organization Owner'), ('org_admin', 'Organization Admin'), ('staff', 'Staff / Teacher'), ('student', 'Student')], db_index=True, help_text="User's role within this organization.", max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive members cannot access organization resources.')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['organization', 'user'],
            },
        ),
        migrations.CreateModel(
            name='ResourceAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('course', 'Course'), ('track', 'Exam Track'), ('exam', 'Exam')], db_index=True, max_length=20)),
                ('source', models.CharField(choices=[('public', 'Public'), ('individual', 'Individual Purchase'), ('organization', 'Organization Assignment'), ('admin', 'Administrator')], db_index=True, max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_key', models.CharField(editable=False, max_length=255, unique=True)),
            ],
            options={
                'ordering': ['-granted_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_key', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for this assignment.', unique=True)),
                ('resource_type', models.CharField(choices=[('course', 'Course'), ('track', 'Exam Track'), ('exam', 'Exam')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('started', 'Started'), ('completed', 'Completed'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('cancelled', 'Cancelled')], db_index=True, default='assigned', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Controls whether this assignment is currently active.')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('starts_at', models.DateTimeField(blank=True, db_index=True, help_text='When the student becomes eligible to access the assigned resource.', null=True)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, help_text='Optional deadline for completing the assignment.', null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='When access to the assigned resource expires.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Optional internal note about this assignment.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official organization name.', max_length=255)),
                ('slug', models.SlugField(help_text='Unique platform identifier for the organization.', max_length=255, unique=True)),
                ('org_type', models.CharField(choices=[('school', 'School'), ('college', 'College'), ('institute', 'Training Institute'), ('company', 'Company')], help_text='Type of organization.', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org/logos/')),
                ('primary_color', models.CharField(blank=True, default='', help_text='Primary branding color, e.g. #3273dc.', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive organizations cannot use organization services.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationCourseSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='active', max_length=20)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, help_text='When the subscription was created.')),
                ('starts_at', models.DateTimeField(blank=True, db_index=True, help_text='When access becomes valid.', null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='When access expires. NULL means no expiry.', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Legacy compatibility flag. New business logic should prefer status and is_valid().')),
                ('payment_required', models.BooleanField(default=False)),
                ('payment_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('payment_status', models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='not_required', max_length=20)),
                ('subscribed_by_admin', models.BooleanField(db_index=True, default=False, help_text='Indicates that the subscription was granted manually by an administrator.')),
                ('auto_renew', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('resource_type', models.CharField(choices=[('course', 'Course'), ('track', 'Exam Track'), ('exam', 'Exam')], db_index=True, max_length=20)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_subscriptions', to='courses.course')),
            ],
        ),
    ]
