# Generated by Django 6.0 on 2026-09-05 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('organizations', '0001_initial'),
        ('quiz', '0001_initial'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationcoursesubscription',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_subscriptions', to='quiz.exam'),
        ),
        migrations.AddField(
            model_name='organizationcoursesubscription',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_subscriptions', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationcoursesubscription',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_subscriptions', to='quiz.examtrack'),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourceaccess',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_access_records', to='courses.course'),
        ),
        migrations.AddField(
            model_name='resourceaccess',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_access_records', to='quiz.exam'),
        ),
        migrations.AddField(
            model_name='resourceaccess',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_access', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='resourceaccess',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_access', to='subscriptions.subscription'),
        ),
        migrations.AddField(
            model_name='resourceaccess',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_access_records', to='quiz.examtrack'),
        ),
        migrations.AddField(
            model_name='resourceaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourceassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='Organization admin or staff member who created the assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_assignments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourceassignment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_assignments', to='courses.course'),
        ),
        migrations.AddField(
            model_name='resourceassignment',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_assignments', to='quiz.exam'),
        ),
        migrations.AddField(
            model_name='resourceassignment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_assignments', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='resourceassignment',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_assignments_revoked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourceassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_resource_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourceassignment',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_assignments', to='quiz.examtrack'),
        ),
        migrations.AddField(
            model_name='resourceaccess',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_access', to='organizations.resourceassignment'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_active', 'org_type'], name='org_active_type_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationcoursesubscription',
            index=models.Index(fields=['organization', 'status'], name='organizatio_organiz_44613b_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationcoursesubscription',
            index=models.Index(fields=['organization', 'resource_type'], name='organizatio_organiz_535e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationcoursesubscription',
            index=models.Index(fields=['organization', 'expires_at'], name='organizatio_organiz_50d23a_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationcoursesubscription',
            constraint=models.UniqueConstraint(fields=('organization', 'course'), name='unique_org_course_subscription'),
        ),
        migrations.AddConstraint(
            model_name='organizationcoursesubscription',
            constraint=models.UniqueConstraint(fields=('organization', 'track'), name='unique_org_track_subscription'),
        ),
        migrations.AddConstraint(
            model_name='organizationcoursesubscription',
            constraint=models.UniqueConstraint(fields=('organization', 'exam'), name='unique_org_exam_subscription'),
        ),
        migrations.AddIndex(
            model_name='organizationmember',
            index=models.Index(fields=['organization', 'is_active'], name='org_member_active_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmember',
            index=models.Index(fields=['organization', 'role', 'is_active'], name='org_member_role_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmember',
            index=models.Index(fields=['user', 'is_active'], name='org_member_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationmember',
            constraint=models.UniqueConstraint(fields=('user', 'organization'), name='unique_org_member'),
        ),
        migrations.AddIndex(
            model_name='resourceassignment',
            index=models.Index(fields=['organization', 'student', 'is_active'], name='res_assign_org_stu_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceassignment',
            index=models.Index(fields=['organization', 'resource_type', 'is_active'], name='res_assign_org_type_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceassignment',
            index=models.Index(fields=['student', 'resource_type', 'is_active'], name='res_assign_stu_type_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceassignment',
            index=models.Index(fields=['organization', 'status'], name='res_assign_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceassignment',
            index=models.Index(fields=['due_at', 'is_active'], name='res_assign_due_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceassignment',
            index=models.Index(fields=['expires_at', 'is_active'], name='res_assign_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceaccess',
            index=models.Index(fields=['user', 'resource_type', 'is_active'], name='res_access_user_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceaccess',
            index=models.Index(fields=['organization', 'resource_type', 'is_active'], name='res_access_org_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceaccess',
            index=models.Index(fields=['subscription', 'is_active'], name='res_access_sub_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceaccess',
            index=models.Index(fields=['assignment', 'is_active'], name='res_access_assign_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceaccess',
            index=models.Index(fields=['expires_at', 'is_active'], name='res_access_exp_idx'),
        ),
    ]
