# Generated by Django 6.0 on 2026-09-15 16:04

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('organizations', '0001_initial'),
        ('quiz', '0001_initial'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classresourceassignment',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_resource_assignments', to='quiz.exam'),
        ),
        migrations.AddField(
            model_name='classresourceassignment',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_resource_assignments', to='quiz.examtrack'),
        ),
        migrations.AddField(
            model_name='classsection',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='organizations.academicyear'),
        ),
        migrations.AddField(
            model_name='classresourceassignment',
            name='class_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_assignments', to='organizations.classsection'),
        ),
        migrations.AddField(
            model_name='classteacher',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='organizations.academicyear'),
        ),
        migrations.AddField(
            model_name='classteacher',
            name='class_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='organizations.classsection'),
        ),
        migrations.AddField(
            model_name='classteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_class_teachings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created the organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guardian',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='classteacher',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teachers', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='classsection',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_sections', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='classresourceassignment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_resource_assignments', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationaccessrequest',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationaccessrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_organization_access_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationaccessrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_access_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationauditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationauditlog',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationclass',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='classsection',
            name='class_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='organizations.organizationclass'),
        ),
        migrations.AddField(
            model_name='organizationcoursesubscription',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_subscriptions', to='courses.course'),
        ),
        migrations.AddField(
            model_name='organizationcoursesubscription',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_subscriptions', to='quiz.exam'),
        ),
        migrations.AddField(
            model_name='organizationcoursesubscription',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_subscriptions', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationcoursesubscription',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_subscriptions', to='quiz.examtrack'),
        ),
        migrations.AddField(
            model_name='organizationdomain',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_domains', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationportalconfig',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_config', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationportfoliosection',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_sections', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationstudent',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationstudent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_student_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourceaccess',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_access_records', to='courses.course'),
        ),
        migrations.AddField(
            model_name='resourceaccess',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_access_records', to='quiz.exam'),
        ),
        migrations.AddField(
            model_name='resourceaccess',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_access', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='resourceaccess',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_access', to='subscriptions.subscription'),
        ),
        migrations.AddField(
            model_name='resourceaccess',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_access_records', to='quiz.examtrack'),
        ),
        migrations.AddField(
            model_name='resourceaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourceassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='Organization admin or staff member who created the assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_assignments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourceassignment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_assignments', to='courses.course'),
        ),
        migrations.AddField(
            model_name='resourceassignment',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_assignments', to='quiz.exam'),
        ),
        migrations.AddField(
            model_name='resourceassignment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_assignments', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='resourceassignment',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_assignments_revoked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourceassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_resource_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourceassignment',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_assignments', to='quiz.examtrack'),
        ),
        migrations.AddField(
            model_name='resourceaccess',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_access', to='organizations.resourceassignment'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='organizations.academicyear'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='class_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='organizations.classsection'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='organizations.organizationstudent'),
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to='organizations.guardian'),
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to='organizations.organizationstudent'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_active', 'org_type'], name='org_active_type_idx'),
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['organization', 'name'], name='org_guardian_name_idx'),
        ),
        migrations.AddIndex(
            model_name='classteacher',
            index=models.Index(fields=['organization', 'teacher', 'is_active'], name='org_teacher_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='classteacher',
            constraint=models.UniqueConstraint(fields=('teacher', 'class_section', 'subject'), name='class_teacher_subject_unique'),
        ),
        migrations.AddIndex(
            model_name='classresourceassignment',
            index=models.Index(fields=['organization', 'class_section', 'is_active'], name='class_res_assign_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='classresourceassignment',
            constraint=models.UniqueConstraint(fields=('class_section', 'resource_type', 'course', 'track', 'exam'), name='class_resource_assignment_unique'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='org_academic_year_unique'),
        ),
        migrations.AddIndex(
            model_name='organizationaccessrequest',
            index=models.Index(fields=['status', 'created_at'], name='organizatio_status_ca0e36_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationaccessrequest',
            index=models.Index(fields=['organization', 'status'], name='organizatio_organiz_523b01_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationaccessrequest',
            index=models.Index(fields=['user', 'status'], name='organizatio_user_id_13c73c_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationauditlog',
            index=models.Index(fields=['organization', 'created_at'], name='org_audit_org_date_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationauditlog',
            index=models.Index(fields=['organization', 'action'], name='org_audit_org_action_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationclass',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='org_class_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='classsection',
            constraint=models.UniqueConstraint(fields=('academic_year', 'class_group', 'name'), name='academic_section_unique'),
        ),
        migrations.AddIndex(
            model_name='organizationcoursesubscription',
            index=models.Index(fields=['organization', 'status'], name='organizatio_organiz_44613b_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationcoursesubscription',
            index=models.Index(fields=['organization', 'resource_type'], name='organizatio_organiz_535e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationcoursesubscription',
            index=models.Index(fields=['organization', 'expires_at'], name='organizatio_organiz_50d23a_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationcoursesubscription',
            constraint=models.UniqueConstraint(fields=('organization', 'course'), name='unique_org_course_subscription'),
        ),
        migrations.AddConstraint(
            model_name='organizationcoursesubscription',
            constraint=models.UniqueConstraint(fields=('organization', 'track'), name='unique_org_track_subscription'),
        ),
        migrations.AddConstraint(
            model_name='organizationcoursesubscription',
            constraint=models.UniqueConstraint(fields=('organization', 'exam'), name='unique_org_exam_subscription'),
        ),
        migrations.AddIndex(
            model_name='organizationdomain',
            index=models.Index(fields=['organization', 'is_verified'], name='org_domain_verified_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationdomain',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('domain'), name='org_domain_ci_unique'),
        ),
        migrations.AddIndex(
            model_name='organizationmember',
            index=models.Index(fields=['organization', 'is_active'], name='org_member_active_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmember',
            index=models.Index(fields=['organization', 'role', 'is_active'], name='org_member_role_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmember',
            index=models.Index(fields=['user', 'is_active'], name='org_member_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationmember',
            constraint=models.UniqueConstraint(fields=('user', 'organization'), name='unique_org_member'),
        ),
        migrations.AddIndex(
            model_name='organizationportfoliosection',
            index=models.Index(fields=['organization', 'is_enabled', 'display_order'], name='org_portal_section_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationstudent',
            index=models.Index(fields=['organization', 'status'], name='org_student_status_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationstudent',
            index=models.Index(fields=['organization', 'student_id'], name='org_student_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationstudent',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='org_student_user_unique'),
        ),
        migrations.AddIndex(
            model_name='resourceassignment',
            index=models.Index(fields=['organization', 'student', 'is_active'], name='res_assign_org_stu_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceassignment',
            index=models.Index(fields=['organization', 'resource_type', 'is_active'], name='res_assign_org_type_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceassignment',
            index=models.Index(fields=['student', 'resource_type', 'is_active'], name='res_assign_stu_type_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceassignment',
            index=models.Index(fields=['organization', 'status'], name='res_assign_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceassignment',
            index=models.Index(fields=['due_at', 'is_active'], name='res_assign_due_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceassignment',
            index=models.Index(fields=['expires_at', 'is_active'], name='res_assign_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceaccess',
            index=models.Index(fields=['user', 'resource_type', 'is_active'], name='res_access_user_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceaccess',
            index=models.Index(fields=['organization', 'resource_type', 'is_active'], name='res_access_org_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceaccess',
            index=models.Index(fields=['subscription', 'is_active'], name='res_access_sub_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceaccess',
            index=models.Index(fields=['assignment', 'is_active'], name='res_access_assign_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceaccess',
            index=models.Index(fields=['expires_at', 'is_active'], name='res_access_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['student', 'academic_year', 'status'], name='student_enrollment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['class_section', 'status'], name='section_enrollment_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentguardian',
            constraint=models.UniqueConstraint(fields=('student', 'guardian'), name='student_guardian_unique'),
        ),
    ]
