# Generated by Django 6.0 on 2026-02-06 14:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_courseassignment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganizationMembership',
            new_name='OrganizationMember',
        ),
        migrations.RenameIndex(
            model_name='organizationmember',
            new_name='organizatio_user_id_02d190_idx',
            old_name='organizatio_user_id_f058b7_idx',
        ),
    ]
