# Generated by Django 6.0 on 2026-03-05 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_alter_course_is_public_alter_course_is_published_and_more'),
        ('organizations', '0005_courseaccess'),
        ('quiz', '0049_alter_category_options_alter_domain_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('course', 'Course'), ('track', 'Exam Track'), ('exam', 'Exam')], max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_students', to='courses.course')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_students', to='quiz.exam')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_assignments', to='organizations.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_resource_assignments', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_students', to='quiz.examtrack')),
            ],
        ),
        migrations.DeleteModel(
            name='CourseAssignment',
        ),
        migrations.AddConstraint(
            model_name='resourceassignment',
            constraint=models.UniqueConstraint(fields=('student', 'organization', 'course'), name='unique_student_course_assignment'),
        ),
        migrations.AddConstraint(
            model_name='resourceassignment',
            constraint=models.UniqueConstraint(fields=('student', 'organization', 'track'), name='unique_student_track_assignment'),
        ),
        migrations.AddConstraint(
            model_name='resourceassignment',
            constraint=models.UniqueConstraint(fields=('student', 'organization', 'exam'), name='unique_student_exam_assignment'),
        ),
    ]
