# Generated by Django 6.0 on 2026-03-05 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_alter_course_is_public_alter_course_is_published_and_more'),
        ('organizations', '0006_resourceassignment_delete_courseassignment_and_more'),
        ('quiz', '0049_alter_category_options_alter_domain_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organizationcoursesubscription',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='organizationcoursesubscription',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_subscriptions', to='quiz.exam'),
        ),
        migrations.AddField(
            model_name='organizationcoursesubscription',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_subscriptions', to='quiz.examtrack'),
        ),
        migrations.AlterField(
            model_name='organizationcoursesubscription',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_subscriptions', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='organizationcoursesubscription',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_subscriptions', to='organizations.organization'),
        ),
        migrations.AddConstraint(
            model_name='organizationcoursesubscription',
            constraint=models.UniqueConstraint(fields=('organization', 'course'), name='unique_org_course_subscription'),
        ),
        migrations.AddConstraint(
            model_name='organizationcoursesubscription',
            constraint=models.UniqueConstraint(fields=('organization', 'track'), name='unique_org_track_subscription'),
        ),
        migrations.AddConstraint(
            model_name='organizationcoursesubscription',
            constraint=models.UniqueConstraint(fields=('organization', 'exam'), name='unique_org_exam_subscription'),
        ),
    ]
