# Generated by Django 6.0 on 2026-03-05 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_alter_course_is_public_alter_course_is_published_and_more'),
        ('organizations', '0007_alter_organizationcoursesubscription_unique_together_and_more'),
        ('quiz', '0049_alter_category_options_alter_domain_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resourceassignment',
            name='unique_student_course_assignment',
        ),
        migrations.RemoveConstraint(
            model_name='resourceassignment',
            name='unique_student_track_assignment',
        ),
        migrations.RemoveConstraint(
            model_name='resourceassignment',
            name='unique_student_exam_assignment',
        ),
        migrations.AlterField(
            model_name='resourceassignment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='resourceassignment',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.exam'),
        ),
        migrations.AlterField(
            model_name='resourceassignment',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.examtrack'),
        ),
        migrations.AddConstraint(
            model_name='resourceassignment',
            constraint=models.UniqueConstraint(fields=('student', 'organization', 'course'), name='unique_student_course'),
        ),
        migrations.AddConstraint(
            model_name='resourceassignment',
            constraint=models.UniqueConstraint(fields=('student', 'organization', 'track'), name='unique_student_track'),
        ),
        migrations.AddConstraint(
            model_name='resourceassignment',
            constraint=models.UniqueConstraint(fields=('student', 'organization', 'exam'), name='unique_student_exam'),
        ),
    ]
