# Generated by Django 6.0 on 2026-03-05 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_alter_course_is_public_alter_course_is_published_and_more'),
        ('organizations', '0008_remove_resourceassignment_unique_student_course_assignment_and_more'),
        ('quiz', '0049_alter_category_options_alter_domain_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('course', 'Course'), ('track', 'Exam Track'), ('exam', 'Exam')], max_length=20)),
                ('source', models.CharField(choices=[('public', 'Public'), ('individual', 'Individual Purchase'), ('organization', 'Organization Assignment')], max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.exam')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.examtrack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'resource_type', 'course', 'track', 'exam', 'source', 'organization')},
            },
        ),
        migrations.DeleteModel(
            name='CourseAccess',
        ),
    ]
