# Generated by Django 6.0 on 2026-03-29 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_alter_course_is_public_alter_course_is_published_and_more'),
        ('organizations', '0010_organizationgroup_organizationmember_group'),
        ('quiz', '0049_alter_category_options_alter_domain_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceassignment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_assignments', to='organizations.organizationgroup'),
        ),
        migrations.AlterField(
            model_name='resourceassignment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_resource_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='resourceassignment',
            constraint=models.UniqueConstraint(fields=('group', 'organization', 'course'), name='unique_group_course'),
        ),
        migrations.AddConstraint(
            model_name='resourceassignment',
            constraint=models.UniqueConstraint(fields=('group', 'organization', 'track'), name='unique_group_track'),
        ),
        migrations.AddConstraint(
            model_name='resourceassignment',
            constraint=models.UniqueConstraint(fields=('group', 'organization', 'exam'), name='unique_group_exam'),
        ),
    ]
