# Generated by Django 6.0 on 2026-02-06 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_rename_organizationmembership_organizationmember_and_more'),
        ('pages', '0002_staticpage_feedback_is_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
    ]
