# Generated by Django 6.0 on 2026-02-05 11:40

import phone_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, help_text='Country of residence', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='accepted_policy',
            field=models.BooleanField(default=False, help_text='User accepted terms & privacy policy'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31, null=True),
        ),
    ]
