# Generated by Django 6.0 on 2026-09-05 12:11

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('owner_type', models.CharField(choices=[('platform', 'Platform'), ('organization', 'Organization')], db_index=True, default='platform', max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='If enabled, an approved and published course may be visible publicly.')),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('approval_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('changes_required', 'Changes Required'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('certificate_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='active', max_length=20)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, help_text='When the subscription was created.')),
                ('starts_at', models.DateTimeField(blank=True, db_index=True, help_text='When access becomes valid.', null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='When access expires. NULL means no expiry.', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Legacy compatibility flag. New business logic should prefer status and is_valid().')),
                ('payment_required', models.BooleanField(default=False)),
                ('payment_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('payment_status', models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='not_required', max_length=20)),
                ('subscribed_by_admin', models.BooleanField(db_index=True, default=False, help_text='Indicates that the subscription was granted manually by an administrator.')),
                ('auto_renew', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('quiz', 'Quiz'), ('organization', 'Organization'), ('admin', 'Admin')], default='quiz', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('lesson_type', models.CharField(choices=[('video', 'Video'), ('article', 'Article'), ('quiz', 'Quiz'), ('practice', 'Practice')], max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('article_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Supports text, images, code blocks, diagrams')),
                ('practice_difficulty', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20, null=True)),
                ('practice_threshold', models.PositiveIntegerField(default=10)),
                ('practice_lock_filters', models.BooleanField(default=True)),
                ('practice_require_correct', models.BooleanField(default=False)),
                ('practice_min_accuracy', models.PositiveIntegerField(blank=True, null=True)),
                ('quiz_completion_mode', models.CharField(choices=[('attempt', 'Any attempt'), ('pass', 'Must pass'), ('score', 'Minimum score')], default='attempt', max_length=20)),
                ('quiz_min_score', models.PositiveIntegerField(default=0)),
                ('quiz_allow_mock', models.BooleanField(default=False)),
                ('quiz_max_attempts', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('video_seconds_watched', models.PositiveIntegerField(default=0)),
                ('video_duration', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
