# Generated by Django 6.0 on 2026-01-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursecertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='video_duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='video_seconds_watched',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
