# Generated by Django 6.0 on 2026-01-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lessonprogress_video_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='practice_lock_filters',
            field=models.BooleanField(default=True, help_text='Lock domain/category filters when practice is launched from course'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='practice_min_accuracy',
            field=models.PositiveIntegerField(blank=True, help_text='Optional minimum accuracy % to complete practice lesson', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='practice_require_correct',
            field=models.BooleanField(default=False, help_text='Require correct answers to count toward threshold'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='practice_threshold',
            field=models.PositiveIntegerField(default=10, help_text='Number of questions to practice before lesson is marked completed'),
        ),
    ]
