# Generated by Django 6.0 on 2026-01-29 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson_practice_lock_filters_and_more'),
        ('quiz', '0029_remove_coursesection_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='practice_difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], help_text='Optional difficulty filter when practice is launched from course', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='practice_domain',
            field=models.ForeignKey(blank=True, help_text='Domain for course-linked practice', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.domain'),
        ),
    ]
