# Generated by Django 6.0 on 2026-01-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_practice_difficulty_lesson_practice_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='quiz_allow_mock',
            field=models.BooleanField(default=False, help_text='Allow mock exam when started from course'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='quiz_completion_mode',
            field=models.CharField(choices=[('attempt', 'Any attempt'), ('pass', 'Must pass'), ('score', 'Minimum score')], default='attempt', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='quiz_max_attempts',
            field=models.PositiveIntegerField(default=0, help_text='0 = unlimited (course-only restriction)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='quiz_min_score',
            field=models.PositiveIntegerField(default=0, help_text='Used only if completion mode = score'),
        ),
    ]
