# Generated by Django 6.0 on 2026-02-02 18:44

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lesson_quiz_allow_mock_lesson_quiz_completion_mode_and_more'),
        ('quiz', '0029_remove_coursesection_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecertificate',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='courseenrollment',
            name='courses_cou_user_id_147840_idx',
        ),
        migrations.RemoveIndex(
            model_name='courseenrollment',
            name='courses_cou_is_acti_15eac1_idx',
        ),
        migrations.RemoveIndex(
            model_name='lessonprogress',
            name='courses_les_user_id_83b81f_idx',
        ),
        migrations.RemoveIndex(
            model_name='lessonprogress',
            name='courses_les_complet_d92e22_idx',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='practice_difficulty',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='article_content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Supports text, images, code blocks, diagrams'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='practice_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.domain'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='practice_lock_filters',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='practice_min_accuracy',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='practice_require_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='practice_threshold',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='quiz_allow_mock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='quiz_max_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='quiz_min_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
