# Generated by Django 6.0 on 2026-02-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_coursecertificate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='practice_difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], help_text='Optional difficulty filter when practice is launched from course', max_length=20, null=True),
        ),
    ]
