# Generated by Django 6.0 on 2026-02-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_subscriptionplan_alter_course_subscription_plans_and_more'),
        ('quiz', '0033_useranswer_started_at_useranswer_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subscription_plans',
            field=models.ManyToManyField(blank=True, related_name='course_access_courses', to='quiz.subscriptionplan'),
        ),
    ]
