# Generated by Django 6.0 on 2026-02-16 15:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_lesson_created_at_lesson_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='article_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Supports text, images, code blocks, diagrams'),
        ),
    ]
