# Generated by Django 6.0 on 2026-02-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_lesson_article_content'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursesection',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddIndex(
            model_name='coursesection',
            index=models.Index(fields=['course', 'order'], name='courses_cou_course__24d4c4_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursesection',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='unique_course_section_order'),
        ),
    ]
