# Generated by Django 6.0 on 2026-02-24 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_course_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesection',
            name='is_deleted',
        ),
    ]
