# Generated by Django 6.0 on 2026-02-24 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_remove_coursesection_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_deleted',
        ),
    ]
