# Generated by Django 6.0 on 2026-02-24 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_remove_course_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_deleted',
        ),
    ]
