# Generated by Django 6.0 on 2026-03-04 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_remove_lesson_is_deleted'),
        ('organizations', '0005_courseaccess'),
        ('quiz', '0049_alter_category_options_alter_domain_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If true, course visible outside organization'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='course',
            name='owner_type',
            field=models.CharField(choices=[('platform', 'Platform'), ('organization', 'Organization')], db_index=True, default='platform', max_length=20),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['owner_type'], name='courses_cou_owner_t_bc166a_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['organization'], name='courses_cou_organiz_e21838_idx'),
        ),
    ]
