# Generated by Django 6.0 on 2026-06-10 18:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_alter_course_is_public_alter_course_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Supports text, images, code blocks, diagrams'),
        ),
    ]
