# Generated by Django 6.0 on 2026-06-11 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_alter_course_description'),
        ('quiz', '0050_alter_exam_options_exam_exam_type_exam_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='quiz.domain'),
        ),
    ]
