# Generated by Django 6.0 on 2026-09-15 16:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('organizations', '0001_initial'),
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(help_text='Unique internal identifier for this plan.', max_length=100, unique=True)),
                ('scope', models.CharField(choices=[('resource', 'Resource'), ('all_access', 'All Access')], db_index=True, default='resource', help_text='Legacy scope retained for migration compatibility.', max_length=20)),
                ('product_type', models.CharField(choices=[('course', 'Course'), ('track', 'Track'), ('account', 'Account')], db_index=True, default='course', help_text='What this plan sells: a Course, Track, or Account.', max_length=20)),
                ('access_mode', models.CharField(choices=[('single_resource', 'Single Resource'), ('limited_access', 'Limited Access'), ('all_access', 'All Access')], db_index=True, default='single_resource', help_text='Account plans may be limited by selectable Course/Track quotas or all-access.', max_length=20)),
                ('max_courses', models.PositiveIntegerField(blank=True, help_text='Maximum Courses selectable for a limited Account plan. NULL means not applicable/unlimited by this field.', null=True)),
                ('max_tracks', models.PositiveIntegerField(blank=True, help_text='Maximum Tracks selectable for a limited Account plan. NULL means not applicable/unlimited by this field.', null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('duration_days', models.PositiveIntegerField(blank=True, help_text='Legacy duration in days. NULL means lifetime for legacy plans.', null=True)),
                ('interval_unit', models.CharField(blank=True, choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year'), ('lifetime', 'Lifetime')], db_index=True, help_text='Billing interval unit. Use Lifetime for one-time lifetime access.', max_length=10, null=True)),
                ('interval_count', models.PositiveIntegerField(blank=True, help_text='Number of interval units in one billing period. Not used for Lifetime.', null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='subscriptio_is_acti_dd0689_idx'), models.Index(fields=['scope', 'is_active'], name='subscriptio_scope_240a07_idx'), models.Index(fields=['product_type', 'access_mode', 'is_active'], name='subscriptio_product_51b036_idx'), models.Index(fields=['interval_unit', 'is_active'], name='subscriptio_interva_92d888_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='active', max_length=20)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('starts_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('payment_status', models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='not_required', max_length=20)),
                ('payment_id', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('subscribed_by_admin', models.BooleanField(db_index=True, default=False)),
                ('auto_renew', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions_granted', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Successful'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('provider', models.CharField(choices=[('manual', 'Manual'), ('razorpay', 'Razorpay'), ('stripe', 'Stripe'), ('other', 'Other')], db_index=True, default='manual', max_length=30)),
                ('transaction_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('order_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('refund_reference', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_payments', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_payments', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subscription', 'status'], name='subscriptio_subscri_0bac84_idx'), models.Index(fields=['provider', 'transaction_id'], name='subscriptio_provide_906124_idx'), models.Index(fields=['organization', 'status'], name='subscriptio_organiz_bbb19b_idx'), models.Index(fields=['user', 'status'], name='subscriptio_user_id_9c57a2_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccountSubscriptionSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_subscription_selections', to='courses.course')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_subscription_selections', to='quiz.examtrack')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_selections', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['subscription', 'course'], name='acct_sel_sub_course_idx'), models.Index(fields=['subscription', 'track'], name='acct_sel_sub_track_idx')],
                'constraints': [models.UniqueConstraint(fields=('subscription', 'course'), name='unique_account_subscription_course'), models.UniqueConstraint(fields=('subscription', 'track'), name='unique_account_subscription_track')],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('course', 'Course'), ('track', 'Exam Track'), ('exam', 'Exam (Legacy)')], db_index=True, max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_entitlements', to='courses.course')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_entitlements', to='quiz.exam')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='subscriptions.subscription')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_entitlements', to='quiz.examtrack')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subscription', 'is_active'], name='sub_ent_sub_active_idx'), models.Index(fields=['resource_type', 'is_active'], name='sub_ent_type_active_idx'), models.Index(fields=['course'], name='sub_ent_course_idx'), models.Index(fields=['track'], name='sub_ent_track_idx'), models.Index(fields=['exam'], name='sub_ent_exam_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('course__isnull', False), ('exam__isnull', True), ('resource_type', 'course'), ('track__isnull', True)), models.Q(('course__isnull', True), ('exam__isnull', True), ('resource_type', 'track'), ('track__isnull', False)), models.Q(('course__isnull', True), ('exam__isnull', False), ('resource_type', 'exam'), ('track__isnull', True)), _connector='OR'), name='valid_subscription_entitlement_resource')],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status'], name='subscriptio_user_id_2a19e8_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['organization', 'status'], name='subscriptio_organiz_3cb096_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['plan', 'status'], name='subscriptio_plan_id_f7cbce_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['expires_at', 'status'], name='subscriptio_expires_9e8e71_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', True), ('user__isnull', False)), models.Q(('organization__isnull', False), ('user__isnull', True)), _connector='OR'), name='subscription_exactly_one_owner'),
        ),
    ]
