# Generated by Django 6.0

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    # Course itself is created by courses.0001. The dependency on
    # courses.0002 was circular because courses.0002 adds the
    # Course.subscription_plans M2M field pointing back to SubscriptionPlan.
    # Keeping this migration at courses.0001 lets courses.0002 depend on
    # subscriptions.0001 and completes the graph without a cycle.
    dependencies = [
        ("courses", "0001_initial"),
        ("organizations", "0001_initial"),
        ("quiz", "0003_government_exam_catalog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("code", models.SlugField(help_text="Unique internal identifier for this plan.", max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("duration_days", models.PositiveIntegerField(blank=True, help_text="NULL means lifetime access.", null=True)),
                ("price", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [models.Index(fields=["is_active"], name="sub_plan_active_idx")],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("pending", "Pending"), ("active", "Active"), ("suspended", "Suspended"), ("cancelled", "Cancelled"), ("expired", "Expired")], db_index=True, default="active", max_length=20)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                ("starts_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("payment_status", models.CharField(choices=[("not_required", "Not Required"), ("pending", "Pending"), ("paid", "Paid"), ("failed", "Failed"), ("refunded", "Refunded")], db_index=True, default="not_required", max_length=20)),
                ("payment_id", models.CharField(blank=True, db_index=True, default="", max_length=150)),
                ("subscribed_by_admin", models.BooleanField(db_index=True, default=False)),
                ("auto_renew", models.BooleanField(default=False)),
                ("cancellation_reason", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="subscriptions", to="organizations.organization")),
                ("plan", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="subscriptions", to="subscriptions.subscriptionplan")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="subscriptions", to=settings.AUTH_USER_MODEL)),
                ("granted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="subscriptions_granted", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "status"], name="sub_user_status_idx"),
                    models.Index(fields=["organization", "status"], name="sub_org_status_idx"),
                    models.Index(fields=["plan", "status"], name="sub_plan_status_idx"),
                    models.Index(fields=["expires_at", "status"], name="sub_exp_status_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=(models.Q(user__isnull=False, organization__isnull=True) | models.Q(user__isnull=True, organization__isnull=False)),
                        name="subscription_exactly_one_owner",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionEntitlement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("resource_type", models.CharField(choices=[("course", "Course"), ("track", "Exam Track"), ("exam", "Exam")], db_index=True, max_length=20)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subscription", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="entitlements", to="subscriptions.subscription")),
                ("course", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="subscription_entitlements", to="courses.course")),
                ("track", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="subscription_entitlements", to="quiz.examtrack")),
                ("exam", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="subscription_entitlements", to="quiz.exam")),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["subscription", "is_active"], name="sub_ent_sub_active_idx"),
                    models.Index(fields=["resource_type", "is_active"], name="sub_ent_type_active_idx"),
                    models.Index(fields=["course"], name="sub_ent_course_idx"),
                    models.Index(fields=["track"], name="sub_ent_track_idx"),
                    models.Index(fields=["exam"], name="sub_ent_exam_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=(
                            models.Q(resource_type="course", course__isnull=False, track__isnull=True, exam__isnull=True)
                            | models.Q(resource_type="track", course__isnull=True, track__isnull=False, exam__isnull=True)
                            | models.Q(resource_type="exam", course__isnull=True, track__isnull=True, exam__isnull=False)
                        ),
                        name="valid_subscription_entitlement_resource",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("pending", "Pending"), ("success", "Successful"), ("failed", "Failed"), ("refunded", "Refunded"), ("partially_refunded", "Partially Refunded"), ("cancelled", "Cancelled")], db_index=True, default="pending", max_length=30)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("provider", models.CharField(choices=[("manual", "Manual"), ("razorpay", "Razorpay"), ("stripe", "Stripe"), ("other", "Other")], db_index=True, default="manual", max_length=30)),
                ("transaction_id", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("order_id", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("refunded_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                ("refund_reference", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("subscription", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payments", to="subscriptions.subscription")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="subscription_payments", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="subscription_payments", to="organizations.organization")),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["subscription", "status"], name="sub_payment_status_idx"),
                    models.Index(fields=["provider", "transaction_id"], name="sub_payment_txn_idx"),
                    models.Index(fields=["organization", "status"], name="sub_payment_org_status_idx"),
                    models.Index(fields=["user", "status"], name="sub_payment_user_status_idx"),
                ],
            },
        ),
    ]
