# Generated by Django 6.0 on 2026-09-08 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="payment",
            new_name="subscriptio_subscri_0bac84_idx",
            old_name="sub_payment_status_idx",
        ),
        migrations.RenameIndex(
            model_name="payment",
            new_name="subscriptio_provide_906124_idx",
            old_name="sub_payment_txn_idx",
        ),
        migrations.RenameIndex(
            model_name="payment",
            new_name="subscriptio_organiz_bbb19b_idx",
            old_name="sub_payment_org_status_idx",
        ),
        migrations.RenameIndex(
            model_name="payment",
            new_name="subscriptio_user_id_9c57a2_idx",
            old_name="sub_payment_user_status_idx",
        ),
        migrations.RenameIndex(
            model_name="subscription",
            new_name="subscriptio_user_id_2a19e8_idx",
            old_name="sub_user_status_idx",
        ),
        migrations.RenameIndex(
            model_name="subscription",
            new_name="subscriptio_organiz_3cb096_idx",
            old_name="sub_org_status_idx",
        ),
        migrations.RenameIndex(
            model_name="subscription",
            new_name="subscriptio_plan_id_f7cbce_idx",
            old_name="sub_plan_status_idx",
        ),
        migrations.RenameIndex(
            model_name="subscription",
            new_name="subscriptio_expires_9e8e71_idx",
            old_name="sub_exp_status_idx",
        ),
        migrations.RenameIndex(
            model_name="subscriptionplan",
            new_name="subscriptio_is_acti_dd0689_idx",
            old_name="sub_plan_active_idx",
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
