# Generated by Django 6.0 on 2026-08-15 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0004_delete_subscriptionplan'),
        ('quiz', '0003_alter_examtrack_pricing_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('resource_type', models.CharField(choices=[('course', 'Course'), ('track', 'Track'), ('exam', 'Exam')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('gateway', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('gateway_order_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('gateway_payment_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='courses.course')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='quiz.exam')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='quiz.examtrack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(db_index=True, max_length=50)),
                ('gateway_transaction_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='created', max_length=20)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.paymentorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(db_index=True, max_length=50)),
                ('event_id', models.CharField(db_index=True, max_length=255)),
                ('event_type', models.CharField(blank=True, default='', max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('signature', models.TextField(blank=True, default='')),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processing_error', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['gateway', 'processed'], name='payments_pa_gateway_2dfdd9_idx')],
                'constraints': [models.UniqueConstraint(fields=('gateway', 'event_id'), name='unique_payment_webhook_event')],
            },
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['user', 'status'], name='payments_pa_user_id_367e5d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['gateway', 'gateway_order_id'], name='payments_pa_gateway_81c37c_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['gateway', 'gateway_payment_id'], name='payments_pa_gateway_7bb41f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['gateway', 'gateway_transaction_id'], name='payments_pa_gateway_a15119_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['order', 'status'], name='payments_pa_order_i_ed562a_idx'),
        ),
    ]
